[package]
name = "foldable"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/keccak-state"

[lib]
path = "lib.rs"

[dependencies]
zeroize = { version = "1.6.0", optional = true }

[features]
zeroize-on-drop = ["zeroize"]
