[package]
name = "rand"
version = "0.8.0" # tungstenite 0.19.0
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/keccak-state"

[lib]
path = "lib.rs"

[dependencies]
cshake = { path = "../cshake", features = ["zeroize-on-drop", "rand"] }
